# This is a simple workflow example for GitHub predefined variables.

name: Github Predefined Environment Variables workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:


jobs:
  print_env_variables_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: env
      
  print_env_variables_windows:
    runs-on: windows-latest
    steps:
          - run: env
  print_env_variables_macos:
    runs-on: macos-latest
    steps:
      - run: env
