# This is a simple workflow example for GitHub predefined variables.

name: Github Predefined Environment Variables workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:


jobs:
  print_env_variables_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: env
      
  print_env_variables_windows:
    runs-on: windows-latest
    steps:
          - run: env
  print_env_variables_macos:
    runs-on: macos-latest
    steps:
      - run: env
  print_deafault_github_variables:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
