# This is a basic workflow template for a GitHub Actions workflow.

name: A basic workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  name: "Foke"
  day: "Friday"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a script
        run: echo ${{ env.name }} ${{ env.day }}
      - name: Push to another repository
        uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to production"
      - name: Deploy2
        run: |
          echo "This is an in-job env variable: ${{ env.namee }} ${{ env.dayy }}"
        env:
          namee: "Peniel"
          dayy: "Saturday"
